#import = [
#  "~/.config/alacritty/themes/themes/oceanic_next.toml"
#:]

[bell]
animation = "EaseOutExpo"
duration = 0

[cursor]
blink_interval = 500
blink_timeout = 5
unfocused_hollow = false

#[cursor.style]
#shape = "Block"

[env]
TERM = "xterm-256color"

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 19

[window]
#decorations = "Buttonless"
opacity = 0.8
blur = true
padding.x = 8
padding.y = 8


#[terminal]
#osc52 = "CopyPaste"

