import = [
  "~/.config/alacritty/themes/themes/catppuccin_frappe.toml"
]

[bell]
animation = "EaseOutExpo"
duration = 0

[window]
decorations = "Buttonless"
padding.x = 8
padding.y = 8

[font]
normal.family = "BlexMono Nerd Font Mono"
size = 14
normal.style = "Italic"

[cursor]
blink_interval = 500
blink_timeout = 5
unfocused_hollow = false

[cursor.style]
shape = "Block"

[terminal]
osc52 = "CopyPaste"

